name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow triggered by ${{ github.event_name }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls ${{ github.workspace }}
